version: '3'
services: 
  monitoria-app:
    build: .
    environment:
      env_file: .env
      NODE_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    container_name: monitoria-app